#!/bin/bash
# Here do anything needed to install the service
# i.e. apt-get install -y foo  or  bzr branch http://myserver/mycode /srv/webroot
# Make sure this hook exits cleanly and is idempotent, common problems here are
# failing to account for a debconf question on a dependency, or trying to pull
# from github without installing git first.
set -e
juju-log "KAM-NEW: install"
apt update
apt install grep
apt install -y kamailio kamailio-mysql-modules
juju-log "KAM-NEW: kamailio installed"
status-set maintenance  "installing kamailio"
status-set blocked "waiting for database"
